---
- name: Create app directiory
  file:
    path: /home/ubuntu/app
    state: directory

- name: Extract files to remote (EC2 instance)
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/app

- name: install dependencies
  become: true
  shell: |
    cd /home/ubuntu/app
    npm install

- name: Start node server daemon with pm2
  become: true
  shell: |
    cd /home/ubuntu/app
    pm2 stop default
    pm2 start npm -- start
  register: starting_server

- debug:
    msg: "{{ starting_server.stdout_lines }}"